version: '3.1'
services:
  paojeda:
    image: mysql:5.7
    volumes: 
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: franco19
      MYSQL_DATABASE: paojeda
      MYSQL_USER: fran
      MYSQL_PASSWORD: franco19
    ports:
      - 3314:3306

